---

# - hosts: all
#   pre_tasks:
#     - name: remove localhost from hosts
#       lineinfile:
#         path: /etc/hosts
#         regexp: '127\.0\.1\.1.*{{inventory_hostname}}.*{{inventory_hostname}}'
#         state: absent
#         owner: root
#         group: root
#         mode: 0644

- hosts: all
  become: yes
  roles:
    - java
    - zookeeper

