---
required_libs_oracle:
  - dirmngr

required_libs_openjdk:
  - ca-certificates-java
  - openjdk-8-jre-headless
  - libcups2

java_repo_openjdk: "deb http://http.debian.net/debian"

# Older versions requires login to be downloaded
# http://www.oracle.com/technetwork/java/archive-139210.html
java_oracle_jdk_latest_versions_urls:
  1.8.0_181:
    url: http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz
    sha256: 1845567095bfbfebd42ed0d09397939796d05456290fb20a83c476ba09f991d3 # https://www.oracle.com/webfolder/s/digest/8u181checksum.html
  10.0.2:
    url: http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.tar.gz
    sha256: 6633c20d53c50c20835364d0f3e172e0cbbce78fff81867488f22a6298fa372b # https://www.oracle.com/webfolder/s/digest/10-0-2checksum.html

